In [22]:
# import packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [23]:
# load data

movies = pd.read_csv('IMDB Horror movies.csv')
pd.options.display.max_columns = None
movies.head(1)

,Title,Year,Genre-Horror,Genre-Thriller,Genre-Sci-Fi,Genre-Mystery,Genre-Romance,Genre-Fantasy,Genre-Comdey,Genre-Drama,Genre-Crime,Genre-War,Genre-Western,Genre-Musical,Genre-Family,Genre-Adventure,Genre-Sport,Genre-History,Release Date,Release Country,Movie Rating,Review Rating,Movie Run Time,Plot,Cast,Language,Filming Locations,Budget
0,Gut,2012.0,Horror,Thriller,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,26-Oct-12,USA,NaN,3.9,91 min,"Directed by Elias. With Jason Vail, Nicholas W...",Jason Vail|Nicholas Wilder|Sarah Schoofs|Kirst...,English,"New York, USA",NaN

## Data Wrangling

In [24]:
# Dropping columns: Filming Locations and Budget

movies= movies.drop(['Filming Locations', 'Budget'], axis = 1)
movies.dropna(inplace=True)
movies.head(1)

,Title,Year,Genre-Horror,Genre-Thriller,Genre-Sci-Fi,Genre-Mystery,Genre-Romance,Genre-Fantasy,Genre-Comdey,Genre-Drama,Genre-Crime,Genre-War,Genre-Western,Genre-Musical,Genre-Family,Genre-Adventure,Genre-Sport,Genre-History,Release Date,Release Country,Movie Rating,Review Rating,Movie Run Time,Plot,Cast,Language
3,Treasure Chest of Horrors II,2013.0,Horror,Thriller,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,23-Apr-13,USA,NOT RATED,3.7,82 min,"Directed by M. Kelley, Shawn C. Phillips, Alex...",Veronica Ricci|Nicholas Adam Clark|James Culle...,English

In [25]:
# Split column: Plot

movies1 = movies['Plot'].str.split('.', expand = True).rename(columns = lambda x: 'Directors' + str(x + 1))
movies1.rename(columns = {'Directors1' : 'Directors1', 'Directors2' : 'Cast1', 'Directors3' : 'Plot1'}, inplace = True)
movies1 = movies1[['Directors1', 'Cast1', 'Plot1']]
movies1.head(1)

      Directors1             Cast1                   Plot1
3  Directed by M   Kelley, Shawn C   Phillips, Alex Powers

In [26]:
# Concat datasets: movies and movies1

movies2 = pd.concat([movies, movies1], axis = 1, keys = ['Title', 'Directors'])
movies2.head(1)

                           Title                                      \
                           Title    Year Genre-Horror Genre-Thriller
3  Treasure Chest of Horrors II   2013.0       Horror       Thriller

                                                                       \
  Genre-Sci-Fi Genre-Mystery Genre-Romance Genre-Fantasy Genre-Comdey
3     NO GENRE      NO GENRE      NO GENRE      NO GENRE     NO GENRE

                                                                              \
  Genre-Drama Genre-Crime Genre-War Genre-Western Genre-Musical Genre-Family
3    NO GENRE    NO GENRE  NO GENRE      NO GENRE      NO GENRE     NO GENRE

                                                                          \
  Genre-Adventure Genre-Sport Genre-History Release Date Release Country
3        NO GENRE    NO GENRE      NO GENRE    23-Apr-13             USA

                                             \
  Movie Rating Review Rating Movie Run Time
3    NOT RATED           3.7         82 min

                                                      \
                                                Plot
3  Directed by M. Kelley, Shawn C. Phillips, Alex...

                                                                   Directors  \
                                                Cast Language     Directors1
3  Veronica Ricci|Nicholas Adam Clark|James Culle...  English  Directed by M


              Cast1                   Plot1
3   Kelley, Shawn C   Phillips, Alex Powers

## Exporting dataframe: newMovies to an csv file.

In [ ]:
movies2.to_csv("newMovies.csv", index = False) #Python

# loading Data frime: newMovies

In [27]:
newMovies = pd.read_csv('newMovies.csv')
pd.options.display.max_columns = None
newMovies.head(1)

,Title,Year,Genre-Horror,Genre-Thriller,Genre-Sci-Fi,Genre-Mystery,Genre-Romance,Genre-Fantasy,Genre-Comdey,Genre-Drama,Genre-Crime,Genre-War,Genre-Western,Genre-Musical,Genre-Family,Genre-Adventure,Genre-Sport,Genre-History,Release Date,Release Country,Movie Rating,Review Rating,Movie Run Time,Plot,Cast,Language,Directors1,Cast1,Plot1
0,Treasure Chest of Horrors II,2013,Horror,Thriller,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,23-Apr-13,USA,NOT RATED,3.7,82 min,"Directed by M. Kelley, Shawn C. Phillips, Alex...",Veronica Ricci|Nicholas Adam Clark|James Culle...,English,Directed by M,"Kelley, Shawn C","Phillips, Alex Powers"

## Data Wrangling newMovies.csv

In [28]:
newMovies= newMovies.drop(['Plot', 'Cast'], axis = 1)
newMovies.head(1)

,Title,Year,Genre-Horror,Genre-Thriller,Genre-Sci-Fi,Genre-Mystery,Genre-Romance,Genre-Fantasy,Genre-Comdey,Genre-Drama,Genre-Crime,Genre-War,Genre-Western,Genre-Musical,Genre-Family,Genre-Adventure,Genre-Sport,Genre-History,Release Date,Release Country,Movie Rating,Review Rating,Movie Run Time,Language,Directors1,Cast1,Plot1
0,Treasure Chest of Horrors II,2013,Horror,Thriller,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,23-Apr-13,USA,NOT RATED,3.7,82 min,English,Directed by M,"Kelley, Shawn C","Phillips, Alex Powers"

In [29]:
newMovies= newMovies.drop(['Title','Genre-Horror', 'Genre-Thriller','Genre-Sci-Fi', 'Genre-Mystery', 'Genre-Romance', 'Genre-Fantasy',
              'Genre-Comdey', 'Genre-Drama', 'Genre-Crime', 'Genre-War', 'Genre-Western', 'Genre-Musical', 'Genre-Family',
              'Genre-Adventure', 'Genre-Sport', 'Genre-History', 'Release Date', 'Movie Rating', 'Movie Run Time',
              'Language', 'Directors1', 'Cast1', 'Plot1'], axis = 1)
newMovies.head(1)

   Year Release Country  Review Rating
0  2013             USA            3.7

## Machine Learning

In [30]:
# Subsetting: Release Country 
x = newMovies.drop('Release Country', axis=1)
y = newMovies['Release Country']

In [31]:
# Spliting the data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [32]:
# Random Tree
nmovie = RandomForestClassifier(n_estimators=500)
nmovie.fit(x_train, y_train)

RandomForestClassifier(n_estimators=500)

In [33]:
moviePredictions = nmovie.predict(x_test)
print(confusion_matrix(y_test, moviePredictions))

[[  0   0   0 ...   2   0   0]
 [  0   0   0 ...   1   0   0]
 [  0   0   0 ...   1   0   0]
 ...
 [  0   0   0 ... 280   0   0]
 [  0   0   0 ...   1   0   0]
 [  0   0   0 ...   1   0   0]]

In [99]:
print(classification_report(y_test, moviePredictions))

                      precision    recall  f1-score   support

           Argentina       0.00      0.00      0.00         1
           Australia       0.00      0.00      0.00         2
             Bahrain       0.00      0.00      0.00         1
             Belgium       0.00      0.00      0.00         2
              Brazil       0.00      0.00      0.00         1
              Canada       0.00      0.00      0.00         4
               Chile       0.00      0.00      0.00         1
               China       0.00      0.00      0.00         1
               Egypt       0.00      0.00      0.00         1
              France       0.00      0.00      0.00         5
             Germany       0.25      0.12      0.17         8
               India       0.00      0.00      0.00         3
             Ireland       0.00      0.00      0.00         1
               Japan       0.00      0.00      0.00        10
              Kuwait       0.00      0.00      0.00         5
            Malaysia       0.00      0.00      0.00         1
              Mexico       0.00      0.00      0.00         1
         Netherlands       0.00      0.00      0.00         2
              Norway       0.00      0.00      0.00         1
                Peru       0.00      0.00      0.00         1
         Philippines       0.50      0.12      0.20         8
              Poland       0.00      0.00      0.00         4
              Russia       0.00      0.00      0.00         3
         South Korea       0.00      0.00      0.00         4
               Spain       0.00      0.00      0.00         3
              Sweden       0.00      0.00      0.00         2
         Switzerland       0.00      0.00      0.00         1
              Taiwan       0.00      0.00      0.00         1
              Turkey       0.00      0.00      0.00         3
                  UK       0.00      0.00      0.00        17
                 USA       0.76      0.90      0.83       301
United Arab Emirates       0.00      0.00      0.00         1
             Vietnam       0.00      0.00      0.00         1

            accuracy                           0.68       401
           macro avg       0.05      0.03      0.04       401
        weighted avg       0.59      0.68      0.63       401

C:\Users\19192\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

The classification_report show that the USA, UK, and Japan are the top 3 countries that release
movies between 1923 to 2017. USA is the highest and released 301 movies during this time frame.

From the classification report the USA precision score is 76% accuracy for positively predicting movies release in the USA. 
During this test the recall value perdicts that 90% of positive cases was caught.
And 83% of positive cases were perdicted.

The UK release a total of 17 horror movies during the same time period and this test predicted 0% accuracy rate for 
positively perdicting movies released in the UK. Theire recall value is at 0% perdicting positie cases was caught.
This model perdicted that 0% of positive cases were predicted. Out of the 17 movies released none was caught positive.

Japan released a tota of 10 horror movies during this time period and this model perdicted that 0% accuracy rate for 
positively perdicting movies released in Japan. Their recall value is 0% perdicting positive cases was caught.
For Japan this model perdicted that 0% of positive case were perdicted.

???In general this model is not highly accurrate with a .05 macro avg score of perdictions.

## Working with ANOVAs

In [34]:
# Loading data frame
anovaMovies = pd.read_csv('newMovies.csv')
pd.options.display.max_columns = None
anovaMovies.head(1)

,Title,Year,Genre-Horror,Genre-Thriller,Genre-Sci-Fi,Genre-Mystery,Genre-Romance,Genre-Fantasy,Genre-Comdey,Genre-Drama,Genre-Crime,Genre-War,Genre-Western,Genre-Musical,Genre-Family,Genre-Adventure,Genre-Sport,Genre-History,Release Date,Release Country,Movie Rating,Review Rating,Movie Run Time,Plot,Cast,Language,Directors1,Cast1,Plot1
0,Treasure Chest of Horrors II,2013,Horror,Thriller,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,23-Apr-13,USA,NOT RATED,3.7,82 min,"Directed by M. Kelley, Shawn C. Phillips, Alex...",Veronica Ricci|Nicholas Adam Clark|James Culle...,English,Directed by M,"Kelley, Shawn C","Phillips, Alex Powers"

## Data Wrangling: anovaMovies

In [35]:
anovaMovies = anovaMovies.drop(['Plot', 'Cast', 'Directors1', 'Cast1', 'Plot1'], axis = 1)
anovaMovies.head(1)

,Title,Year,Genre-Horror,Genre-Thriller,Genre-Sci-Fi,Genre-Mystery,Genre-Romance,Genre-Fantasy,Genre-Comdey,Genre-Drama,Genre-Crime,Genre-War,Genre-Western,Genre-Musical,Genre-Family,Genre-Adventure,Genre-Sport,Genre-History,Release Date,Release Country,Movie Rating,Review Rating,Movie Run Time,Language
0,Treasure Chest of Horrors II,2013,Horror,Thriller,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,NO GENRE,23-Apr-13,USA,NOT RATED,3.7,82 min,English

In [36]:
# sum the column in anovaMovies

for column in anovaMovies.columns:
    print("\n" + column)
    print(anovaMovies[column].value_counts())

Title
Amnesiac                          2
Silent But Deadly                 2
Shame the Devil                   2
Toxin                             2
Rape Zombie: Lust of the Dead     2
                                 ..
The Demon's Rook                  1
Drink Me                          1
Some Guy Who Kills People         1
I Spit on Your Grave 2            1
Queen of Blood                    1
Name: Title, Length: 1322, dtype: int64

Year
2014    272
2013    258
2015    231
2012    224
2016    179
2017     75
2011     59
2010     16
2009      8
2006      3
2008      3
2007      1
1999      1
1998      1
1991      1
1979      1
1973      1
1923      1
Name: Year, dtype: int64

Genre-Horror
 Horror    1335
Name: Genre-Horror, dtype: int64

Genre-Thriller
NO GENRE     921
 Thriller    404
Thriller      10
Name: Genre-Thriller, dtype: int64

Genre-Sci-Fi
NO GENRE    1235
 Sci-Fi       99
Sci-Fi         1
Name: Genre-Sci-Fi, dtype: int64

Genre-Mystery
NO GENRE    1248
 Mystery      85
Mystery        2
Name: Genre-Mystery, dtype: int64

Genre-Romance
NO GENRE    1300
 Romance      35
Name: Genre-Romance, dtype: int64

Genre-Fantasy
NO GENRE    1310
 Fantasy      25
Name: Genre-Fantasy, dtype: int64

Genre-Comdey
NO GENRE    1329
 Comedy        6
Name: Genre-Comdey, dtype: int64

Genre-Drama
NO GENRE    1326
 Drama         9
Name: Genre-Drama, dtype: int64

Genre-Crime
NO GENRE    1333
 Crime         2
Name: Genre-Crime, dtype: int64

Genre-War
NO GENRE    1330
 War           5
Name: Genre-War, dtype: int64

Genre-Western
NO GENRE    1328
 Western       7
Name: Genre-Western, dtype: int64

Genre-Musical
NO GENRE    1326
 Musical       9
Name: Genre-Musical, dtype: int64

Genre-Family
NO GENRE    1331
 Family        4
Name: Genre-Family, dtype: int64

Genre-Adventure
NO GENRE      1331
 Adventure       4
Name: Genre-Adventure, dtype: int64

Genre-Sport
NO GENRE    1333
 Sport         2
Name: Genre-Sport, dtype: int64

Genre-History
NO GENRE    1335
Name: Genre-History, dtype: int64

Release Date
16-Oct-15    11
2016         10
6-Oct-15      8
2014          8
2013          8
             ..
21-Jan-12     1
26-Sep-15     1
21-Dec-13     1
8-May-15      1
23-Sep-14     1
Name: Release Date, Length: 789, dtype: int64

Release Country
USA                     985
UK                       66
Japan                    41
Philippines              22
Germany                  21
Russia                   16
France                   14
Kuwait                   14
Spain                    13
India                    10
Canada                   10
Italy                     9
Netherlands               9
South Korea               8
Mexico                    8
Australia                 7
Sweden                    6
Turkey                    5
Poland                    5
Peru                      5
Belgium                   5
Ireland                   4
China                     4
Brazil                    4
Argentina                 3
Norway                    3
Taiwan                    3
Singapore                 2
Chile                     2
Venezuela                 2
United Arab Emirates      2
Indonesia                 2
Hungary                   2
Bahrain                   2
Austria                   2
Ukraine                   2
New Zealand               2
Belarus                   1
Thailand                  1
Malaysia                  1
Qatar                     1
Denmark                   1
Vietnam                   1
Switzerland               1
Serbia                    1
Latvia                    1
Colombia                  1
Egypt                     1
Finland                   1
Israel                    1
Czech Republic            1
Hong Kong                 1
Name: Release Country, dtype: int64

Movie Rating
NOT RATED    640
R            387
TV-MA         99
UNRATED       96
PG-13         75
TV-14         31
PG             5
X              1
NC-17          1
Name: Movie Rating, dtype: int64

Review Rating
4.7    53
5.1    47
4.3    47
5.2    45
4.5    44
       ..
8.3     1
8.2     1
7.2     1
1.4     1
8.6     1
Name: Review Rating, Length: 70, dtype: int64

Movie Run Time
90 min     119
89 min      67
86 min      61
88 min      55
80 min      54
          ...
151 min      1
140 min      1
69 min       1
156 min      1
111 min      1
Name: Movie Run Time, Length: 81, dtype: int64

Language
English                                    1123
Japanese                                     20
Spanish                                      18
English|Spanish                              17
German                                        8
                                           ...
Mandarin|Japanese                             1
Chinese                                       1
English|French|Latin                          1
English|Spanish|Chinese|Scottish Gaelic       1
English|Spanish|Latin|Italian                 1
Name: Language, Length: 97, dtype: int64

In [37]:
anovaMovies1 = anovaMovies['Release Date'].str.split('-', expand = True).rename(columns = lambda x: 'Release Date' + str(x + 1))
anovaMovies1.rename(columns = {'Release Date1' : 'Day', 'Release Date2' : 'Month', 'Release Date3' : 'Year'}, inplace = True)
anovaMovies1 = anovaMovies1[['Day', 'Month']]
anovaMovies1.head(1)

  Day Month
0  23   Apr

In [38]:
anovaMovies2 = anovaMovies['Movie Run Time'].str.split(' ', expand = True).rename(columns = lambda x: 'Movie Run Time' + str(x + 1))
anovaMovies2.rename(columns = {'Movie Run Time1' : 'Movie Length', 'Movie Run Time2' : 'min'}, inplace = True)
anovaMovies2 = anovaMovies2[['Movie Length', 'min']]
anovaMovies2.head(1)

  Movie Length  min
0           82  min

In [39]:
# Concat datasets: movies and movies1

anovaMovies3a = pd.concat([anovaMovies, anovaMovies1, anovaMovies2], axis = 1, keys = ['Title', 'Day', 'Movie Length'])
anovaMovies3a.head(1)

                           Title                                    \
                           Title  Year Genre-Horror Genre-Thriller
0  Treasure Chest of Horrors II   2013       Horror       Thriller

                                                                       \
  Genre-Sci-Fi Genre-Mystery Genre-Romance Genre-Fantasy Genre-Comdey
0     NO GENRE      NO GENRE      NO GENRE      NO GENRE     NO GENRE

                                                                              \
  Genre-Drama Genre-Crime Genre-War Genre-Western Genre-Musical Genre-Family
0    NO GENRE    NO GENRE  NO GENRE      NO GENRE      NO GENRE     NO GENRE

                                                                          \
  Genre-Adventure Genre-Sport Genre-History Release Date Release Country
0        NO GENRE    NO GENRE      NO GENRE    23-Apr-13             USA

                                                     Day       Movie Length  \
  Movie Rating Review Rating Movie Run Time Language Day Month Movie Length
0    NOT RATED           3.7         82 min  English  23   Apr           82


   min
0  min

In [40]:
# Dropping rows without values

anovaMovies3a.dropna(inplace=True)
anovaMovies3a.head(1)

                           Title                                    \
                           Title  Year Genre-Horror Genre-Thriller
0  Treasure Chest of Horrors II   2013       Horror       Thriller

                                                                       \
  Genre-Sci-Fi Genre-Mystery Genre-Romance Genre-Fantasy Genre-Comdey
0     NO GENRE      NO GENRE      NO GENRE      NO GENRE     NO GENRE

                                                                              \
  Genre-Drama Genre-Crime Genre-War Genre-Western Genre-Musical Genre-Family
0    NO GENRE    NO GENRE  NO GENRE      NO GENRE      NO GENRE     NO GENRE

                                                                          \
  Genre-Adventure Genre-Sport Genre-History Release Date Release Country
0        NO GENRE    NO GENRE      NO GENRE    23-Apr-13             USA

                                                     Day       Movie Length  \
  Movie Rating Review Rating Movie Run Time Language Day Month Movie Length
0    NOT RATED           3.7         82 min  English  23   Apr           82


   min
0  min

In [147]:
# Exporting dataframe: anovaMovies3 to an csv file.
anovaMovies3a.to_csv("anovaMovies3a.csv", index = False) #Python